// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBauwZjvHscwGXv9FpFSHNo-fWUKHnPfqQ',
    appId: '1:758642806980:web:b71f0451a739e2c6287991',
    messagingSenderId: '758642806980',
    projectId: 'signolia',
    authDomain: 'signolia.firebaseapp.com',
    storageBucket: 'signolia.firebasestorage.app',
    measurementId: 'G-RW378DFZYR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdLFootBHHy3j9tffstx4u9x_WRd3O-SU',
    appId: '1:758642806980:android:7e312e1bae95181c287991',
    messagingSenderId: '758642806980',
    projectId: 'signolia',
    storageBucket: 'signolia.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD38z5Rk8gYbmeg3qzjbvV1MWfnQeYKPTc',
    appId: '1:758642806980:ios:2ffc783804b698d2287991',
    messagingSenderId: '758642806980',
    projectId: 'signolia',
    storageBucket: 'signolia.firebasestorage.app',
    iosBundleId: 'com.signolia.signoliaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD38z5Rk8gYbmeg3qzjbvV1MWfnQeYKPTc',
    appId: '1:758642806980:ios:2ffc783804b698d2287991',
    messagingSenderId: '758642806980',
    projectId: 'signolia',
    storageBucket: 'signolia.firebasestorage.app',
    iosBundleId: 'com.signolia.signoliaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBauwZjvHscwGXv9FpFSHNo-fWUKHnPfqQ',
    appId: '1:758642806980:web:b1526ea499e6b848287991',
    messagingSenderId: '758642806980',
    projectId: 'signolia',
    authDomain: 'signolia.firebaseapp.com',
    storageBucket: 'signolia.firebasestorage.app',
    measurementId: 'G-DL1E9PK193',
  );
}
